[tool.poetry]
name = "gideon"
version = "0.1.0"
description = "Artificially Intelligent Personal Assistant"
authors = ["Alejandro Sánchez Yalí <asanchezyali@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.6.1"}
rich = "^12.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
